### ISSUE TITLE
Payload With 11 and 12 char not working eg. [ M: inactive ]

### ISSUE THREAD

**Issue by ihossainuiu** [SATL-Research-and-Development/ETS_PES_issues#3]
W:Tailor-30,M: idle,B:,S5:End, ,break , ,help ,OEE,0,Production,0,Rework,0,Hourly Rate,0,Target,2000,Reject,0
This is working
W:Tailor-30,M: inactive,B:,S5:End, , , , ,OEE,0,Production,0,Rework,0,Hourly Rate,0,Target,2000,Reject,0
Not working

**Comment by wirahim** [comment]
looks to be an issue with scanf. The problem is no longer occurring with manual parsing.
