### ISSUE TITLE
Current Timestamp need to be added on the payload of device sending to server.

### ISSUE THREAD

**Issue by Sazzad19** [SATL-Research-and-Development/ETS_PES_issues#36]

**Comment by wirahim** [comment]
timestamp added in epoch format in all JSON packets.

Startup: 
> {"SrNo":"PES-593","TabNo":"0","RFID":"0","BAT":"StartUP","Time":"1724925754"}

Button: 
>{"SrNo":"PES-593","TabNo":"0","RFID":"00:00:00:00","BAT":"S2","Time":"1724926451"}

NFC: 
>{"SrNo":"PES-593","TabNo":"0","RFID":"37:DE:5F:EA","BAT":"0","Time":"1724926471"}

@Sazzad19 and @MoshiurSarder please check and confirm.
