### ISSUE TITLE
No devices can connect to WiFi router.

### ISSUE THREAD

**Issue by sajib71** [SATL-Research-and-Development/ETS_PES_issues#37]
Tplink E4 Mesh router 
Not connected to mikrotik
Can not access from tplink app.
Can connect to router using mobile.
Ethernet switch is on.
No internet.
Red LED in router.

**Comment by wirahim** [comment]
It appears that the devices could not connect to Broker.

The switch bridging the two TP-Link routers to the MikroTik router is not working. We need to look into the switch. (CUDY GS108D)

**Comment by wirahim** [comment]
https://github.com/user-attachments/assets/56d5f460-383d-4d9e-9918-72317e18c610

**Comment by wirahim** [comment]
It looks like the adapter of the switch is faulty. We are currently testing the switch with a new adapter.

**Comment by wirahim** [comment]
Devices could connect to the router but could not connect to the broker because the switch in between was faulty.
